# Facilities

## 7-Minute Tour of Facilities

Starts at top of stairs on the 4th floor of the
Engineering Building, where the department main
office is located. Then it moves down the stairs
to show some of the posters that highlight recent
student and faculty achievements. After that, it
shows Engineering 4072, which is an open computer
lab that students can use to do homework or 
projects. Then the video shows a common area, also
on the 4th floor of the Engineering Building, where
students meet outside of class and often 
review material or collaborate. That leads to a
typical classroom, Engineering 4066 where we teach
many of our courses. Next is Engineering 4059, which
is out of our computer lecture rooms. This room
features 30 computers that are available to 
students, but hidden inside their desks when they 
are not needed for the lecture. After that is room
224 in the Classroom Building. Classroom 224 is a
typical large lecture room used by our department
and others. Following that is STEM 320, a classroom
that encourages active learning as opposed to 
lecture-style presentations.

<iframe width="560" height="315" src="https://www.youtube.com/embed/OfrVapm8MGc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>

## Engineering 4066

Engineering 4066 is a typical classroom in the 4th floor of the
Engineering building. We teach many of our class there (and in 
similar rooms).

<iframe width="560" height="315" src="https://www.youtube.com/embed/UDEgbRmWuWs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen
data-external="1"></iframe>

## Engineering 2159

Engineering 2159 is a computer lab that is open to students for homework or 
personal use, and that we use to teach some of our lab sections.

<iframe width="560" height="315" src="https://www.youtube.com/embed/J25JPifDqZQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>

