# ABET Depot for the Department of Computer Science at the University of Wyoming

This directory contains information about the ABET accredication process for
the [Department of Computer Science](http://www.cs.uwyo.edu/) at the University of Wyoming. 
Its primary purpose is twofold:

1. *Greater Transparency* by providing a central location where users interested in 
   ABET accredication of our department can see the ongoing process.
2. *Improved Continuity* by allowing all department members and stakeholders to see
   upcoming deadlines and procedures as they prepare for future visits. This will also
   guarantee that if the ABET Coordinator is hit by the proverbial bus, the department's
   ability to continue the assessment process will not be overly affected.

Resources:

* [Tour of Facilities](facilities.html)
* [Evaluation Overview](evaluation.html)
* [Evaluation Schedule](schedule.html)
* Past Evaluation Results
    * [2014-15](results/results-2015.html)
    * [2015-16](results/results-2016.html)
    * [2016-17](results/results-2017.html)
    * [2018-19](results/results-2019.html)
    * [2019-20](results/results-2020.html)
    * [2020-21](results/results-2021.html)
    * [2023-24](results/results-2024.html)


