# ABET Assessment Results for AY 2015-16

```{r echo=FALSE}
num.excelled <- c(
    a1=6+14, a2=6, a3=13, a4=22,
    b2=38,
    c1=27, c2=24, c3=38+18, c4=21, c5=6, 
    d1=17, d2=30, d3=26, d4=6, d5=8,
    e1=24, e2=24, e3=24, e4=22,
    f1=8, f2=33, f3=25,
    g1=24, g2=24,
    h1=24, h2=18, h3=24,
    i1=8, i2=6, i3=19, i4=21,
    j3=21, j4=2, j5=5,
    k1=17, k2=50+42+51+50, k3=38, k4=35)
num.mastered <- c(
    a1=20+1, a2=4, a3=1, a4=0,
    b2=20,
    c1=4, c2=7, c3=20+3, c4=4, c5=14,
    d1=3, d2=0, d3=0, d4=19, d5=18,
    e1=0, e2=0, e3=0, e4=2,
    f1=21, f2=0, f3=8,
    g1=0, g2=0,
    h1=0, h2=8, h3=0,
    i1=13, i2=0, i3=0, i4=12,
    j3=0, j4=10, j5=4,
    k1=9, k2=0+0+0+0, k3=20, k4=0)
num.partially.mastered <- c(
    a1=0+3, a2=2, a3=9, a4=1,
    b2=5,
    c1=0, c2=0, c3=5+4, c4=5, c5=7,
    d1=10, d2=0, d3=7, d4=8, d5=7,
    e1=0, e2=0, e3=0, e4=0,
    f1=4, f2=0, f3=0,
    g1=0, g2=0,
    h1=0, h2=7, h3=0,
    i1=3, i2=0, i3=7, i4=0,
    j3=5, j4=4, j5=4,
    k1=3, k2=1+0+0+0, k3=5, k4=0)
num.below.expectations <- c(
    a1=1+6, a2=12, a3=1, a4=1,
    b2=0,
    c1=4, c2=4, c3=0+8, c4=3, c5=6,
    d1=3, d2=3, d3=0, d4=0, d5=0,
    e1=0, e2=0, e3=0, e4=0,
    f1=0, f2=0, f3=0,
    g1=0, g2=0,
    h1=0, h2=0, h3=0,
    i1=1, i2=6, i3=0, i4=0,
    j3=6, j4=2, j5=3,
    k1=4, k2=12+21+12+13, k3=0, k4=0)

num.excelled['a'] <- sum(num.excelled[paste('a', 1:4, sep="")])
num.excelled['b'] <- sum(num.excelled[paste('b', 2, sep="")])
num.excelled['c'] <- sum(num.excelled[paste('c', 1:5, sep="")])
num.excelled['d'] <- sum(num.excelled[paste('d', 1:5, sep="")])
num.excelled['e'] <- sum(num.excelled[paste('e', 1:4, sep="")])
num.excelled['f'] <- sum(num.excelled[paste('f', 1:3, sep="")])
num.excelled['g'] <- sum(num.excelled[paste('g', 1:2, sep="")])
num.excelled['h'] <- sum(num.excelled[paste('h', 1:3, sep="")])
num.excelled['i'] <- sum(num.excelled[paste('i', 1:4, sep="")])
num.excelled['j'] <- sum(num.excelled[paste('j', 3:5, sep="")])
num.excelled['k'] <- sum(num.excelled[paste('k', 1:4, sep="")])

num.mastered['a'] <- sum(num.mastered[paste('a', 1:4, sep="")])
num.mastered['b'] <- sum(num.mastered[paste('b', 2, sep="")])
num.mastered['c'] <- sum(num.mastered[paste('c', 1:5, sep="")])
num.mastered['d'] <- sum(num.mastered[paste('d', 1:5, sep="")])
num.mastered['e'] <- sum(num.mastered[paste('e', 1:4, sep="")])
num.mastered['f'] <- sum(num.mastered[paste('f', 1:3, sep="")])
num.mastered['g'] <- sum(num.mastered[paste('g', 1:2, sep="")])
num.mastered['h'] <- sum(num.mastered[paste('h', 1:3, sep="")])
num.mastered['i'] <- sum(num.mastered[paste('i', 1:4, sep="")])
num.mastered['j'] <- sum(num.mastered[paste('j', 3:5, sep="")])
num.mastered['k'] <- sum(num.mastered[paste('k', 1:4, sep="")])

num.partially.mastered['a'] <- sum(num.partially.mastered[paste('a', 1:4, sep="")])
num.partially.mastered['b'] <- sum(num.partially.mastered[paste('b', 2, sep="")])
num.partially.mastered['c'] <- sum(num.partially.mastered[paste('c', 1:5, sep="")])
num.partially.mastered['d'] <- sum(num.partially.mastered[paste('d', 1:5, sep="")])
num.partially.mastered['e'] <- sum(num.partially.mastered[paste('e', 1:4, sep="")])
num.partially.mastered['f'] <- sum(num.partially.mastered[paste('f', 1:3, sep="")])
num.partially.mastered['g'] <- sum(num.partially.mastered[paste('g', 1:2, sep="")])
num.partially.mastered['h'] <- sum(num.partially.mastered[paste('h', 1:3, sep="")])
num.partially.mastered['i'] <- sum(num.partially.mastered[paste('i', 1:4, sep="")])
num.partially.mastered['j'] <- sum(num.partially.mastered[paste('j', 3:5, sep="")])
num.partially.mastered['k'] <- sum(num.partially.mastered[paste('k', 1:4, sep="")])

num.below.expectations['a'] <- sum(num.below.expectations[paste('a', 1:4, sep="")])
num.below.expectations['b'] <- sum(num.below.expectations[paste('b', 2, sep="")])
num.below.expectations['c'] <- sum(num.below.expectations[paste('c', 1:5, sep="")])
num.below.expectations['d'] <- sum(num.below.expectations[paste('d', 1:5, sep="")])
num.below.expectations['e'] <- sum(num.below.expectations[paste('e', 1:4, sep="")])
num.below.expectations['f'] <- sum(num.below.expectations[paste('f', 1:3, sep="")])
num.below.expectations['g'] <- sum(num.below.expectations[paste('g', 1:2, sep="")])
num.below.expectations['h'] <- sum(num.below.expectations[paste('h', 1:3, sep="")])
num.below.expectations['i'] <- sum(num.below.expectations[paste('i', 1:4, sep="")])
num.below.expectations['j'] <- sum(num.below.expectations[paste('j', 3:5, sep="")])
num.below.expectations['k'] <- sum(num.below.expectations[paste('k', 1:4, sep="")])

get.excelled <- function (key) {
    pct <- num.excelled[[key]] / (num.excelled[[key]] + num.mastered[[key]] + num.partially.mastered[[key]] + num.below.expectations[[key]])
    return (round(100*pct))
}
get.mastered <- function (key) {
    pct <- num.mastered[[key]] / (num.excelled[[key]] + num.mastered[[key]] + num.partially.mastered[[key]] + num.below.expectations[[key]])
    return (round(100*pct))
}
get.partially.mastered <- function (key) {
    pct <- num.partially.mastered[[key]] / (num.excelled[[key]] + num.mastered[[key]] + num.partially.mastered[[key]] + num.below.expectations[[key]])
    return (round(100*pct))
}
get.below.expectations <- function (key) {
    pct <- num.below.expectations[[key]] / (num.excelled[[key]] + num.mastered[[key]] + num.partially.mastered[[key]] + num.below.expectations[[key]])
    return (round(100*pct))
}
num.assessed <- function (key) {
    num <- num.excelled[[key]] + num.mastered[[key]] + num.partially.mastered[[key]] + num.below.expectations[[key]]
    return (num)
}

history.excelled <- data.frame(
    a=c(62, get.excelled('a')),
    b=c(69, get.excelled('b')),
    c=c(71, get.excelled('c')),
    d=c(66, get.excelled('d')),
    e=c(20, get.excelled('e')),
    f=c(83, get.excelled('f')),
    g=c(20, get.excelled('g')),
    h=c(20, get.excelled('h')),
    i=c(67, get.excelled('i')),
    j=c(79, get.excelled('j')),
    k=c(49, get.excelled('k')))
history.mastered <- data.frame(
    a=c(10, get.mastered('a')),
    b=c(14, get.mastered('b')),
    c=c( 8, get.mastered('c')),
    d=c(17, get.mastered('d')),
    e=c(80, get.mastered('e')),
    f=c( 6, get.mastered('f')),
    g=c(80, get.mastered('g')),
    h=c(80, get.mastered('h')),
    i=c(24, get.mastered('i')),
    j=c(15, get.mastered('j')),
    k=c(15, get.mastered('k')))
history.partially.mastered <- data.frame(
    a=c(12, get.partially.mastered('a')),
    b=c(10, get.partially.mastered('b')),
    c=c(11, get.partially.mastered('c')),
    d=c( 7, get.partially.mastered('d')),
    e=c( 0, get.partially.mastered('e')),
    f=c(11, get.partially.mastered('f')),
    g=c( 0, get.partially.mastered('g')),
    h=c( 0, get.partially.mastered('h')),
    i=c( 3, get.partially.mastered('i')),
    j=c( 2, get.partially.mastered('j')),
    k=c(24, get.partially.mastered('k')))
history.below.expectations <- data.frame(
    a=c(16, get.below.expectations('a')),
    b=c( 7, get.below.expectations('b')),
    c=c(10, get.below.expectations('c')),
    d=c(10, get.below.expectations('d')),
    e=c( 0, get.below.expectations('e')),
    f=c( 0, get.below.expectations('f')),
    g=c( 0, get.below.expectations('g')),
    h=c( 0, get.below.expectations('h')),
    i=c( 6, get.below.expectations('i')),
    j=c( 4, get.below.expectations('j')),
    k=c(12, get.below.expectations('k')))

history.pass <- history.excelled + history.mastered
history.fail <- history.partially.mastered + history.below.expectations
```

## Summary

The data for AY 2015-16 was used in the Department's response
to the ABET evaluation of our program following the ABET Team
Visit on October of 2015. 

Outcome  | % Excelled | % Mastered | % Partially Mastered | % Below Expectations | #Student Assessments
:-------:|-----------:|-----------:|---------------------:|---------------------:|------------------------:
(a)      | `r get.excelled('a')` | `r get.mastered('a')` | `r get.partially.mastered('a')` | `r get.below.expectations('a')` | `r num.assessed('a')`
(b)      | `r get.excelled('b')` | `r get.mastered('b')` | `r get.partially.mastered('b')` | `r get.below.expectations('b')` | `r num.assessed('b')`
(c)      | `r get.excelled('c')` | `r get.mastered('c')` | `r get.partially.mastered('c')` | `r get.below.expectations('c')` | `r num.assessed('c')`
(d)      | `r get.excelled('d')` | `r get.mastered('d')` | `r get.partially.mastered('d')` | `r get.below.expectations('d')` | `r num.assessed('d')`
(e)      | `r get.excelled('e')` | `r get.mastered('e')` | `r get.partially.mastered('e')` | `r get.below.expectations('e')` | `r num.assessed('e')`
(f)      | `r get.excelled('f')` | `r get.mastered('f')` | `r get.partially.mastered('f')` | `r get.below.expectations('f')` | `r num.assessed('f')`
(g)      | `r get.excelled('g')` | `r get.mastered('g')` | `r get.partially.mastered('g')` | `r get.below.expectations('g')`| `r num.assessed('g')`
(h)      | `r get.excelled('h')` | `r get.mastered('h')` | `r get.partially.mastered('h')` | `r get.below.expectations('h')`| `r num.assessed('h')`
(i)      | `r get.excelled('i')` | `r get.mastered('i')` | `r get.partially.mastered('i')` | `r get.below.expectations('i')`| `r num.assessed('i')`
(j)      | `r get.excelled('j')` | `r get.mastered('j')` | `r get.partially.mastered('j')` | `r get.below.expectations('j')`| `r num.assessed('j')`
(k)      | `r get.excelled('k')` | `r get.mastered('k')` | `r get.partially.mastered('k')` | `r get.below.expectations('k')`| `r num.assessed('k')`

Considering Excelled and Mastered to "Satisfy" each student outcome, we can look at historical trends.

Outcome | %Satisfied 2014-15       | %Satisfied 2015-16       | Change
:------:|-------------------------:|-------------------------:|--------------------------------:
(a)     | `r history.pass[1, 'a']` | `r history.pass[2, 'a']` | `r history.pass[2, 'a'] - history.pass[1, 'a']`
(b)     | `r history.pass[1, 'b']` | `r history.pass[2, 'b']` | `r history.pass[2, 'b'] - history.pass[1, 'b']`
(c)     | `r history.pass[1, 'c']` | `r history.pass[2, 'c']` | `r history.pass[2, 'c'] - history.pass[1, 'c']`
(d)     | `r history.pass[1, 'd']` | `r history.pass[2, 'd']` | `r history.pass[2, 'd'] - history.pass[1, 'd']`
(e)     | `r history.pass[1, 'e']` | `r history.pass[2, 'e']` | `r history.pass[2, 'e'] - history.pass[1, 'e']`
(f)     | `r history.pass[1, 'f']` | `r history.pass[2, 'f']` | `r history.pass[2, 'f'] - history.pass[1, 'f']`
(g)     | `r history.pass[1, 'g']` | `r history.pass[2, 'g']` | `r history.pass[2, 'g'] - history.pass[1, 'g']`
(h)     | `r history.pass[1, 'h']` | `r history.pass[2, 'h']` | `r history.pass[2, 'h'] - history.pass[1, 'h']`
(i)     | `r history.pass[1, 'i']` | `r history.pass[2, 'i']` | `r history.pass[2, 'i'] - history.pass[1, 'i']`
(j)     | `r history.pass[1, 'j']` | `r history.pass[2, 'j']` | `r history.pass[2, 'j'] - history.pass[1, 'j']`
(k)     | `r history.pass[1, 'k']` | `r history.pass[2, 'k']` | `r history.pass[2, 'k'] - history.pass[1, 'k']`

As the table shows, the percentage of students who satisfy each outcome is mostly the same in
the two years for which we have data.  The outcomes (j) and (k) show the most difference, and
we attribute this to a better understanding of the assessment process among the faculty, as
opposed to any real change in student performance. We will, of course, continut to monitor
this closely in the next years.

More details of student assessment can be seen by considering the assessment of individual PKIs.

Outcome | KPI    | % Excelled | % Mastered | % Partially Mastered | % Below Expectations | #Student Assessments
:------:|:------:|-----------:|-----------:|---------------------:|---------------------:|--------------------:
(a)     | (a.1)  |  `r get.excelled('a1')` | `r get.mastered('a1')` | `r get.partially.mastered('a1')` | `r get.below.expectations('a1')` | `r num.assessed('a1')`
&nbsp;  | (a.2)  |  `r get.excelled('a2')` | `r get.mastered('a2')` | `r get.partially.mastered('a2')` | `r get.below.expectations('a2')` | `r num.assessed('a2')`
&nbsp;  | (a.3)  |  `r get.excelled('a3')` | `r get.mastered('a3')` | `r get.partially.mastered('a3')` | `r get.below.expectations('a3')` | `r num.assessed('a3')`
&nbsp;  | (a.4)  |  `r get.excelled('a4')` | `r get.mastered('a4')` | `r get.partially.mastered('a4')` | `r get.below.expectations('a4')` | `r num.assessed('a4')`
&nbsp;  | (a.5)  |  * | * | * | * | 0
&nbsp;  | (a.6)  |  * | * | * | * | 0
(b)     | (b.1)  |  * | * | * | * | 0
&nbsp;  | (b.2)  |  `r get.excelled('b2')` | `r get.mastered('b2')` | `r get.partially.mastered('b2')` | `r get.below.expectations('b2')` | `r num.assessed('b2')`
(c)     | (c.1)  |  `r get.excelled('c1')` | `r get.mastered('c1')` | `r get.partially.mastered('c1')` | `r get.below.expectations('c1')` | `r num.assessed('c1')`
&nbsp;  | (c.2)  |  `r get.excelled('c2')` | `r get.mastered('c2')` | `r get.partially.mastered('c2')` | `r get.below.expectations('c2')` | `r num.assessed('c2')`
&nbsp;  | (c.3)  |  `r get.excelled('c3')` | `r get.mastered('c3')` | `r get.partially.mastered('c3')` | `r get.below.expectations('c3')` | `r num.assessed('c3')`
&nbsp;  | (c.4)  |  `r get.excelled('c4')` | `r get.mastered('c4')` | `r get.partially.mastered('c4')` | `r get.below.expectations('c4')` | `r num.assessed('c4')`
&nbsp;  | (c.5)  |  `r get.excelled('c5')` | `r get.mastered('c5')` | `r get.partially.mastered('c5')` | `r get.below.expectations('c5')` | `r num.assessed('c5')`
(d)     | (d.1)  |  `r get.excelled('d1')` | `r get.mastered('d1')` | `r get.partially.mastered('d1')` | `r get.below.expectations('d1')` | `r num.assessed('d1')`
&nbsp;  | (d.2)  |  `r get.excelled('d2')` | `r get.mastered('d2')` | `r get.partially.mastered('d2')` | `r get.below.expectations('d2')` | `r num.assessed('d2')`
&nbsp;  | (d.3)  |  `r get.excelled('d3')` | `r get.mastered('d3')` | `r get.partially.mastered('d3')` | `r get.below.expectations('d3')` | `r num.assessed('d3')`
&nbsp;  | (d.4)  |  `r get.excelled('d4')` | `r get.mastered('d4')` | `r get.partially.mastered('d4')` | `r get.below.expectations('d4')` | `r num.assessed('d4')`
&nbsp;  | (d.5)  |  `r get.excelled('d5')` | `r get.mastered('d5')` | `r get.partially.mastered('d5')` | `r get.below.expectations('d5')` | `r num.assessed('d5')`
(e)     | (e.1)  |  `r get.excelled('e1')` | `r get.mastered('e1')` | `r get.partially.mastered('e1')` | `r get.below.expectations('e1')` | `r num.assessed('e1')`
&nbsp;  | (e.2)  |  `r get.excelled('e2')` | `r get.mastered('e2')` | `r get.partially.mastered('e2')` | `r get.below.expectations('e2')` | `r num.assessed('e2')`
&nbsp;  | (e.3)  |  `r get.excelled('e3')` | `r get.mastered('e3')` | `r get.partially.mastered('e3')` | `r get.below.expectations('e3')` | `r num.assessed('e3')`
&nbsp;  | (e.4)  |  `r get.excelled('e4')` | `r get.mastered('e4')` | `r get.partially.mastered('e4')` | `r get.below.expectations('e4')` | `r num.assessed('e4')`
(f)     | (f.1)  |  `r get.excelled('f1')` | `r get.mastered('f1')` | `r get.partially.mastered('f1')` | `r get.below.expectations('f1')` | `r num.assessed('f1')`
&nbsp;  | (f.2)  |  `r get.excelled('f2')` | `r get.mastered('f2')` | `r get.partially.mastered('f2')` | `r get.below.expectations('f2')` | `r num.assessed('f2')`
&nbsp;  | (f.3)  |  `r get.excelled('f3')` | `r get.mastered('f3')` | `r get.partially.mastered('f3')` | `r get.below.expectations('f3')` | `r num.assessed('f3')`
(g)     | (g.1)  |  `r get.excelled('g1')` | `r get.mastered('g1')` | `r get.partially.mastered('g1')` | `r get.below.expectations('g1')` | `r num.assessed('g1')`
&nbsp;  | (g.2)  |  `r get.excelled('g2')` | `r get.mastered('g2')` | `r get.partially.mastered('g2')` | `r get.below.expectations('g2')` | `r num.assessed('g2')`
(h)     | (h.1)  |  `r get.excelled('h1')` | `r get.mastered('h1')` | `r get.partially.mastered('h1')` | `r get.below.expectations('h1')` | `r num.assessed('h1')`
&nbsp;  | (h.2)  |  `r get.excelled('h2')` | `r get.mastered('h2')` | `r get.partially.mastered('h2')` | `r get.below.expectations('h2')` | `r num.assessed('h2')`
&nbsp;  | (h.3)  |  `r get.excelled('h3')` | `r get.mastered('h3')` | `r get.partially.mastered('h3')` | `r get.below.expectations('h3')` | `r num.assessed('h3')`
(i)     | (i.1)  |  `r get.excelled('i1')` | `r get.mastered('i1')` | `r get.partially.mastered('i1')` | `r get.below.expectations('i1')` | `r num.assessed('i1')`
&nbsp;  | (i.2)  |  `r get.excelled('i2')` | `r get.mastered('i2')` | `r get.partially.mastered('i2')` | `r get.below.expectations('i2')` | `r num.assessed('i2')`
&nbsp;  | (i.3)  |  `r get.excelled('i3')` | `r get.mastered('i3')` | `r get.partially.mastered('i3')` | `r get.below.expectations('i3')` | `r num.assessed('i3')`
&nbsp;  | (i.4)  |  `r get.excelled('i4')` | `r get.mastered('i4')` | `r get.partially.mastered('i4')` | `r get.below.expectations('i4')` | `r num.assessed('i4')`
(j)     | (j.1)  |  * | * | * | * | 0
&nbsp;  | (j.2)  |  * | * | * | * | 0
&nbsp;  | (j.3)  |  `r get.excelled('j3')` | `r get.mastered('j3')` | `r get.partially.mastered('j3')` | `r get.below.expectations('j3')` | `r num.assessed('j3')`
&nbsp;  | (j.4)  |  `r get.excelled('j4')` | `r get.mastered('j4')` | `r get.partially.mastered('j4')` | `r get.below.expectations('j4')` | `r num.assessed('j4')`
&nbsp;  | (j.5)  |  `r get.excelled('j5')` | `r get.mastered('j5')` | `r get.partially.mastered('j5')` | `r get.below.expectations('j5')` | `r num.assessed('j5')`
(k)     | (k.1)  |  `r get.excelled('k1')` | `r get.mastered('k1')` | `r get.partially.mastered('k1')` | `r get.below.expectations('k1')` | `r num.assessed('k1')`
&nbsp;  | (k.2)  |  `r get.excelled('k2')` | `r get.mastered('k2')` | `r get.partially.mastered('k2')` | `r get.below.expectations('k2')` | `r num.assessed('k2')`
&nbsp;  | (k.3)  |  `r get.excelled('k3')` | `r get.mastered('k3')` | `r get.partially.mastered('k3')` | `r get.below.expectations('k3')` | `r num.assessed('k3')`
&nbsp;  | (k.4)  |  `r get.excelled('k4')` | `r get.mastered('k4')` | `r get.partially.mastered('k4')` | `r get.below.expectations('k4')` | `r num.assessed('k4')`

As this table shows, some of the PKIs were not assessed in the current cycle. This is due to a family 
emergency that prevented assessment of COSC 3020 from being complete as of the time of this writing
While this may skew the results a little, the comparisons with last year's assessments lead us to believe that
the final results will be substantially similar.

## Assessment Data

### COSC 1010: Intro to Programming, Allyson Anderson

Core Course                             | KPIs                        | Outcomes
:---------------------------------------|:----------------------------|:--------
COSC 1010: Intro to Programming         | (i.2)                       | (i)

    Performance Indicator (i.2): Program in Java, including use of the Java collections and other useful 
    Java frameworks

    Homework 8:  The salesReport project allows an employee to enter a simple daily sales report and 
    prints out the results. The employee must enter his username and password. After verifying the 
    username and password, the program allows the employee to enter his sales details for the day. 
    Sales details include the product name, product ID#, price, and quantity sold. An object should be 
    created for each product and then added to the daily collection of product objects. When the 
    salesperson is finished entering data, the program calculates the total cash value of the 
    salesperson's sales for the day and prints out the report.  

    There were 12 Computer Science majors in the course, 6 of them did not turn in the assignment. 
    6 students were assessed.
    6 students excelled.

### COSC 2030: Programming II, Tom Bailey

Core Course                             | Assessed
:---------------------------------------|:----------------------------
COSC 2030: Programming II               | Yearly

    Performance Indicator (i.1):  Program in C++, including use of the C++ Standard Library

    Problem 3.2 from Exam 3

    Give a diagram of the storage structure for a Standard Template Library vector. Explain your 
    diagram.

    Give a diagram of the storage structure for a Standard Template Library list. Explain your 
    diagram.

    The STL list class has a method that inserts a new entry at the front of this list object. 
    The STL vector class does not have this method. Why not?

    25 students were assessed.
    8 students excelled.
    13 students mastered.
    3 students partially mastered.
    1 student was below expectations.

---

    Performance Indicator (i.3):  Use an IDE to edit, compile, and debug a program

    Project 01:  Read and process a file of lists of numbers

    Task 

    Write a C++ program that reads lists from a file and reports the name, size, mean if 
    appropriate, and smallest number if appropriate for each list; and reports the list 
    name and sum of the list with the largest sum.

    The file to be read consists of:
        the number of lists in the file,
    then
        zero or more of:
            a list sentinel, a number not equal to any value in this list;
            the list name, readable as a C++ STL string;
            zero or more list values, readable as C++ doubles;
            the list sentinel

    26 students were assessed.

    19 students excelled.
    no students mastered.
    7 students partially mastered.
    no students were below expectations.

### COSC 2300: Discrete Mathematics, John Cowles

Core Course                             | Assessed
:---------------------------------------|:----------------------------
COSC 2300: Discrete Mathematics         | Yearly

    Performance Indicator (a.1): Use descrete mathematics techniques
 
     Quiz 1
       converse & contrapositive
       negations & DeMorgan's laws
 
     27 students were assessed.
 
      6 students excelled.
     20 students mastered.
      0 students partially mastered.
      1 student was below expectations.
     -------------------------------------------------
     Quiz 2 
       direct proof
 
     24 students were assessed.
 
     14 students excelled.
      1 student mastered.
      3 students partially mastered.
      6 students were below expectations.

---

    Performance Indicator (a.2): Estimate cardinality of relevant events
                                 in computing applications
 
     Final Question 7
       count sets, bags, lists, & sorted lists
 
     24 students were assessed.
 
      6 students excelled.
      4 students mastered.
      2 students partially mastered.
     12 students were below expectations.

---

    Performance Indicator (a.3): Use mathematical induction to prove 
                                 mathematical formulas that arise
                                 in computing applications
 
     Final Question 6 
       math. induction proof
 
     24 students were assessed.
 
     13 students excelled.
      1 student mastered.
      9 students partially mastered.
      1 student was below expectations.

---

    Performance Indicator (a.4): Calculate the sum of arithmetic series 
                                 that arise in computing applications
 
     Final Question 2
       Gauss' method for summing arithmetic series
 
     24 students were assessed.
 
     22 students excelled.
      0 students mastered.
      1 student partially mastered.
      1 student was below expectations.

### COSC 3011: Software Design, Kim Buckner

Core Course                             | Assessed
:---------------------------------------|:----------------------------
COSC 3011: Software Design              | Yearly

    Performance Indicator (b.2): Analyze at least two or more proposed solutions 
    to given problem and select the best solution for the given problem.

    This was assessed through the program design project. The teams were required 
    to plan, design, and program a game. This was in five steps over the majority 
    of the semester with the sixth, wrap-up due as the final. The programming 
    assignments are: Program 01, Program 02, Program 03, Program 04, Program 05.
    The assignments build upon the previous solutions to culminate in a graphical
    game of Izzi.

    I have combined the results of the first five steps of the programming project 
    as I did for the course grade.

    63 students were assessed.

    38 students Excelled
    20 students Mastered
    5 students Partially Mastered
    0 students Below Expectations

---

    Performance Indicator (c.3): Design the selected solution for a given problem. 

    This was assessed with the same set of projects as (b.2).

---

    Performance Indicator (k.2): Describe commonly used design patterns.

    This was assessed using several of the quizzes which were given covering student 
    presentations: Visitor Pattern, Factory Pattern, Observer Pattern, Model-View-Controller.

    Visitor pattern:
    63 students were assessed.
    Excelled: 50 students
    Mastered: 0 students
    Partially Mastered: 1 students
    Below Expectations: 12 (most did not take quiz).

    Factory pattern:
    63 students were assessed.
    Excelled: 42 students
    Mastered: 0 students
    Partially Mastered: 0 students
    Below Expectations: 21 (most did not take quiz).

    Observer pattern:
    63 students were assessed.
    Excelled: 51 students
    Mastered: 0 students
    Partially Mastered: 0 students
    Below Expectations: 12 (most did not take quiz).

    Model-View-Controller:
    63 students were assessed.
    Excelled: 50 students
    Mastered: 0 students
    Partially Mastered: 0 students
    Below Expectations: 13 (most did not take quiz).

---

    Performance Indicator (k.3): Design the selected solution for a given problem. 

    This was assessed with the same set of projects as (b.2) and (c.3).

### COSC 3020: Algorithms & Data Structures, Tom Bailey

Core Course                             | Assessed
:---------------------------------------|:----------------------------
COSC 3020: Algorithms & Data Structures | Every other year, starting 2016-17

    Performance Indicator (j.3): Analyze the asymptotic cost of basic graph algorithms

    Lab 07

    Graph methods:  reverse, topological sort

    32 students were assessed.

    21 students excelled.
    0 students mastered.
    5 students partially mastered.
    6 student were below expectations.

---

    Performance Indicator (j.4):  Describe the impact of techniques such as caching 
    and dynamic programming on the performance of algorithms

    Problem 4.1 from Exam 4

    Consider this recursive function:

    int
    test(int n)
    {
        const int terms = 19;

        int sum = 1;
        if (n >= 1)
        {
            for (int i = 1; i <= terms; ++i)
                sum += test(n / (i + 1));
        }
        return sum;
    }

    When called with n = 100,000, the function required more than 25 seconds to 
    make over 900,000,000 recursive calls.

    Sketch the pseudo code for a memorization of this function.  Explain why this 
    version is expected to be much faster than the pure recursive version.

    Why would memorization be better than dynamic programming for this problem?

    18 students were assessed.

    2 students excelled.
    10 students mastered.
    4 students partially mastered.
    2 students were below expectations.

---

    Performance Indicator (j.5):  Understand the difference between polynomial 
    and exponential complexity

    Problem 12 from the Final Exam

        Define the longest increasing subsequence problem.  

        Describe a naïve, brute force solution that solves this problem.

        What is the time complexity of this solution?

        Describe a dynamic programming solution that solves this problem in O(n^2) time.

    16 students were assessed.

    5 students excelled.
    4 students mastered.
    4 students partially mastered.
    3 students were below expectations.

### COSC 3050: Ethics, Kim Buckner

Core Course                             | Assessed
:---------------------------------------|:----------------------------
COSC 3050: Ethics                       | Every other year, starting 2016-17

    Performance Indicator (e.1): Recognize ethical issues involved in a 
    professional setting.

    Case studies/readings/quiz topics: Performance, harassment, professional 
    responsibility.

    24 students were assessed.

    24 students excelled.
    0 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (e.2): Describe current issues in security. 

    Case studies/readings/quiz topic: Security

    24 students were assessed.

    24 students excelled.
    0 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (e.3): Describe current issues in privacy.

    Case studies/readings/quiz topic: Privacy, free speech

    24 students were assessed.

    24 students excelled.
    0 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (e.4): Respect and honor ethics in writing assignments.

    Their final papers were all reasonable, the biggest problems being grammatical errors
    especially for our foreign students. Final paper

    There were 24 students assessed.

    22 students excelled.
    2 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (g.1): Understand the impact of computing solutions on 
    society in a global economic context.
    
    Case studies/readings/quiz: Visas, whistle blowing

    24 students were assessed.

    24 students excelled.
    0 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (g.2): Describe non-technical computing issues such as 
    sustainability, entrepreneurship, and outsourcing.

    Case studies/readings/quiz: Codes of conduct, social society, visas (same from (g.1)) 

    24 students were assessed.

    24 students excelled.
    0 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (h.1): Read and report on papers in the technical literature.

    Same as (e.1), (e.2), (e.3), (e.4), (g.1), (g.2) and the final paper. The assessment 
    of this item is included in the first assessment.

    24 students were assessed.

    24 students excelled.
    0 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (h.3): Review articles, chapters, or presentations from the 
    professional literature.
    
    Same as (e.1), (e.2), (e.3), (e.4), (g.1), (g.2) and the final paper. The assessment 
    of this item is included in the first assessment.

    24 students were assessed.

    24 students excelled.
    0 students mastered.
    0 students partially mastered.
    0 students were below expectations.


### COSC 4950: Senior Design I, Ruben Gamboa

Core Course                             | Assessed
:---------------------------------------|:----------------------------
COSC 4950: Senior Design I              | Every other year, starting 2017-18

This is the first part of the capstone course. Students work in groups
ranging from 3 to 5, and they select a project. In this course, the
students try to flesh out the project, deciding on the important features
and trying to come to terms with project risk.  They decide what technology
to use, and they may start implementation.  They also document their
decisions by writing use cases, or other tools as appropriate (e.g., 
story boards for projects that choose to write games).

Classtime was devoted to group presentations that updated the instructor
and the other teams on the status of the project. This is the main tool
used for assessment.

    Performance Indicator (c.1): Identify constraints on the design problem

    35 students were assessed.

    27 students excelled.
    4 students mastered.
    0 students partially mastered.
    4 students were below expectations.

---

    Performance Indicator (c.2) Establish acceptance criteria for a solution

    35 students were assessed.

    24 students excelled.
    7 students mastered.
    0 students partially mastered.
    4 students were below expectations.

---

    Performance Indicator (k.4) Describe agile methods of software development


    35 students were assessed.

    35 students excelled.
    0 students mastered.
    0 students partially mastered.
    0 students were below expectations.

### COSC 4955: Senior Design II, Ruben Gamboa

Core Course                             | Assessed
:---------------------------------------|:----------------------------
COSC 4955: Senior Design II             | Every other year, starting 2017-18

This is the second part of the capstone course, and students continue
to work in the same groups as in COSC 4950, and they finish the implementation
of the project they started in that class. Students also prepare for the
final presentations, and give a presentation describing their project
to a general audience. Finally, students develop their project using
source code control through github, and they turn in their final projects
by inviting the instructor to the github repository.

Classtime was devoted to group presentations that updated the instructor
and the other teams on the status of the project. This is the main tool
used for assessment. Where indicated, the project source code or the
final presentation is also used for assessment.

(d,4), (d.5), (f.1), (f.2), (f.3), (i.4), (k.1)

    Performance Indicator (c.3): Design the selected solution for a given problem

    33 students were assessed.

    18 students excelled.
    3 students mastered.
    4 students partially mastered.
    8 students were below expectations.

---

    Performance Indicator (c.4): Implement the designed solution for a given problem

    33 students were assessed.

    21 students excelled.
    4 students mastered.
    5 students partially mastered.
    3 students were below expectations.

---

    Performance Indicator (c.5): Evaluate the implemented solution

    33 students were assessed.

    6 students excelled.
    14 students mastered.
    7 students partially mastered.
    6 students were below expectations.

---

    Performance Indicator (d.1): Listen to other team members

    33 students were assessed.

    17 students excelled.
    3 students mastered.
    10 students partially mastered.
    3 students were below expectations.

---

    Performance Indicator (d.2): Actively discuss team projects, 
    objectives, or challenges with other team members

    33 students were assessed.

    30 students excelled.
    0 students mastered.
    0 students partially mastered.
    3 students were below expectations.

---

    Performance Indicator (d.3): Fulfill team duties on time
    
    33 students were assessed.

    26 students excelled.
    0 students mastered.
    7 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (d.4): Share in the work of the team
    
    33 students were assessed.

    6 students excelled.
    19 students mastered.
    8 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (d.5): Research and gather information
    
    33 students were assessed.

    8 students excelled.
    18 students mastered.
    7 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (f.1): Write technical reports

    Assessed using the documentation and project description.
    
    33 students were assessed.

    8 students excelled.
    21 students mastered.
    4 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (f.2): Present technical material to technical peers

    33 students were assessed.

    33 students excelled.
    0 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (f.3): Present technical material to non-technical visitors

    Assessed using the final presentation.
    
    33 students were assessed.

    25 students excelled.
    8 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (h.2): Participate in professional activities
    of a program

    Assessed using ACM Student Chapter meetings, as well as references to
    trade books and conferences during class discussion.
    
    33 students were assessed.

    18 students excelled.
    8 students mastered.
    7 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (i.4): Use source code control to manage different versions 
    of a program

    Assessed using the final project submission.
    
    33 students were assessed.

    21 students excelled.
    12 students mastered.
    0 students partially mastered.
    0 students were below expectations.

---

    Performance Indicator (k.1): Design the overall architecture of a software system

    Assessed using the final project submission and class status reports.
    
    33 students were assessed.

    17 students excelled.
    9 students mastered.
    3 students partially mastered.
    4 students were below expectations.
